### PR TITLE
Fix image repo name in chart

### PR DESCRIPTION
**Pull request by mumoshu**
Ref https://github.com/actions-runner-controller/actions-runner-controller/issues/644#issuecomment-869200869
Fixes https://github.com/actions-runner-controller/actions-runner-controller/issues/662

### CODE REVIEW

**Comment by nyagnik** [comment]
Can this be merged? 
I am also facing the issue.

**Comment by int128** [comment]
Could you bump the chart version for a new release?

**Comment by kirillbilchenko** [comment]
Yes, would be nice to have a new version we are not able to run with the latest version aswell.

**Comment by sledigabel** [comment]
There's a new version for #666 (the ticket of hell apparently), hopefully that should cut a new version of the chart.

**Pull request merged**
