### PR TITLE
Renamed Runner Dockerfiles

### PR DESCRIPTION
**Pull request by Fleshgrinder**
Renamed the runner dockerfiles so that we have proper syntax highlighting for them, as well as a consistent way to map from the image name to the dockerfile. Added a `.dockerignore` file to avoid uploading things to the daemon that we never use.

### CODE REVIEW

**Review by toast-gear — APPROVED** [review]
LGTM @Fleshgrinder resolve the conflicts and we can merge this

**Comment by Fleshgrinder** [comment]
@toast-gear done

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks for your contribution ☺️

**Comment by mumoshu** [comment]
(Re-resolved the conflict and waiting for the CI to pass...

**Pull request merged**
