### PR TITLE
fix 1621:discover runner statuses feature to dind image

### PR DESCRIPTION
**Pull request by bigwheel**
based on https://github.com/actions-runner-controller/actions-runner-controller/issues/1621#issuecomment-1180082270
and https://github.com/actions-runner-controller/actions-runner-controller/commit/11cb9b78829f8640ceb3bcb677e5d608dc3299ea#diff-45ecac98435a59bccdffc03779dd18d22ed154a507be7b20cc0828ed8d1a31b6L119-R122

### CODE REVIEW

**Comment by bigwheel** [comment]
dup #1623

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for your contribution!
I've already merged #1623 but I slightly prefer this as this is more consistent with the other dockerfile! Let me use this as the final result 😄

**Comment by mumoshu** [comment]
> Is this my environment problem ?

Yeah maybe. My quick googling seems to be telling that it might be caused by a network issue in your environment.
https://github.com/microsoft/WSL/issues/5491
https://github.com/actions/virtual-environments/issues/5519

Is that the case for you? 🤔

**Comment by bigwheel** [comment]
> Yeah maybe. My quick googling seems to be telling that it might be caused by a network issue in your environment.
> https://github.com/microsoft/WSL/issues/5491
> https://github.com/actions/virtual-environments/issues/5519
> 
> Is that the case for you? 🤔

Perhaps. I exchanged macbook from intel to m1 in july and docker set up is incompleted (I installed docker for mac to build this today). Ignore my build failure please.

**Review by mumoshu — APPROVED** [review]

**Pull request merged**
