### PR TITLE
Facilitate detection of failed pod creation

### LINKED ISSUE #2888: Facilitate detection of failed pod creation
### What would you like added?

When the runner controller fails to create a pod, I want to be able to see the error only with runner view permissions.

### Why is this needed?

If I don't have permission to view the runner controller logs, there is no way to determine if the creation of the pod for runner failed.

### PR DESCRIPTION
**Pull request by utam0k**
Currently, the only way to see if the pod creation fails is to look at the runner_controller's log. This requires permission to view the namespace where the runner controller is located. Even if you do not have that permission, you should be able to see a log of a Runner you created.

Fix: https://github.com/actions/actions-runner-controller/issues/2888

Example manifest: 
```yaml
$ cat example-runner.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: example-runner
spec:
  repository: utam0k/playground
  containers:
    - name: runner
      resources:
        limits:
          cpu: 2
          memory: 500Mi
          unknown_resource: 2
```

You will be able to confirm why the creation of a pod failed:
```console
$ kubectl get runner -o yaml example-runner
...
status:
  message: 'Failed to create pod resource: Pod "example-runner" is invalid: [spec.containers[0].resources.limits[unknown_resource]:
    Invalid value: "unknown_resource": must be a standard resource type or fully qualified,
    spec.containers[0].resources.limits[unknown_resource]: Invalid value: "unknown_resource":
    must be a standard resource for containers, spec.containers[0].resources.requests[unknown_resource]:
    Invalid value: "unknown_resource": must be a standard resource type or fully qualified,
    spec.containers[0].resources.requests[unknown_resource]: Invalid value: "unknown_resource":
    must be a standard resource for containers]'
  phase: Failed
```

### CODE REVIEW

**Comment by utam0k** [comment]
@nikola-jokic @Link- Hi, maintainers 👋  To whom is it appropriate to ask about this matter?

**Comment by utam0k** [comment]
@MubashirUsman @toast-gear Hi 👋  I am not sure how to proceed with this PR. Please let me know if there is something I am not following the guide 🙏

**Comment by Link-** [comment]
@utam0k - Thank you for your contribution! This is currently not on our backlog. We appreciate your patience as we go through our priorities list. We'll get to this in time.

**Comment by utam0k** [comment]
@Link- Thanks for your reaction 🙏 Where can I asee your priorities list?

**Comment by utam0k** [comment]
@Link- @nikola-jokic I think ARC is a very good project. Is there anything I can do to help?

**Comment by kluz-przemyslaw-sabre** [comment]
Hi @utam0k 
Can You please share what does Your fix do exactly? I've applied it to my ARC fork but it doesn't seem to show any differences. In the case where the runner pod fails before starting (eq. ImagePullBackoff or resource request too high) I don't see any log on the GUI or in the controller or any new events on the k8s namespace.

**Comment by utam0k** [comment]
I reopen this PR if needing it. Time has passed too long.

**Pull request closed without merging**
