### PR TITLE
Add the way to configure bucket size for actions-metric-server

### LINKED ISSUE #2739: Disable high-cardinality tags in the metrics-server
### What would you like added?

A way to stop the metrics-server from tagging metrics with tags of high cardinality.

### Why is this needed?

The metrics-server currently tags metrics with high-cardinality tags like `job_name`, `workflow_name`, `repository`, `head_branch` (see https://github.com/actions/actions-runner-controller/blob/e0a7e142e0fcd446c58e7875d4d44a7eea6e72f2/pkg/actionsmetrics/metrics.go#L79). On top of that it publishes two distribution metrics which have about 45 buckets each (see https://github.com/actions/actions-runner-controller/blob/e0a7e142e0fcd446c58e7875d4d44a7eea6e72f2/pkg/actionsmetrics/metrics.go#L24). Since a separate value is publish for each combination of metric and tags, the number of published values grows very fast.

Example: If you have 10 different jobs names and 5 workflow names across 5 repositories with 5 branches each, you get `10*5*5*5=1250` different values. Since two metrics are distributions with 45 buckets, we get `2*45*1250=112500` values just from those two metrics.

### Additional context

By default when you use Datadog to collect the metrics, it stops at the first 2000 values. The limit can be increased, but the data easily grows to several tens of MBs large per scrape.

If you let me know how you would like this configuration to work (e.g., a toggle per tag?) I'd be happy to open a PR for it.

### PR DESCRIPTION
**Pull request by kirillbilchenko**
Add the way to configure bucket size for actions-metric-server histogram metrics
To set the different bucket need to set the env variable in the values file under `actionsMetricsServer.env`
`PROMETHEUS_RUN_BUCKET_INTERVALS: 1,5,10,300` etc. 
`PROMETHEUS_QUEUE_BUCKET_INTERVALS: 0.5,1,3,5,10,30` etc

resolve https://github.com/actions/actions-runner-controller/issues/2739

### CODE REVIEW

**Comment by MPV** [comment]
If you haven't seen this one already it might be worth looking into as well:
- https://github.com/actions/actions-runner-controller/issues/2873

**Comment by kirillbilchenko** [comment]
> If you haven't seen this one already it might be worth looking into as well:
> 
> * [Runner-scale-set metric cardinality #2873](https://github.com/actions/actions-runner-controller/issues/2873)

@MPV Hey thanks for pointing but in my case metrics relabelling not solving the issue, to relabel prometheus first need to scrape it, in my case the payload produced by metric server with default amount of bucket is 30+ megabyte, so prometheus simply fail to do it. By controlling this on application level I can reduce the amount of produced data and better control the buckets, for example for scheduling I'm not sure if we need to have 3000+ second bucket or even 1800 and 600, because this is already a bad indication that something going wrong with queue.

**Comment by kirillbilchenko** [comment]
@Link- @mumoshu do we need this or we can drop it?

**Comment by Link-** [comment]
As this relates to the community modes, I'll leave it to @mumoshu to take action on this

**Pull request closed without merging**
