### PR TITLE
chart: Allow to disabling kube-rbac-proxy and expose metrics

### LINKED ISSUE #454: Configuring prometheus metrics
I can see that there is prometheus metrics support in the code but couldn't figure out how to configure it. 
Can we have some docs on how to do this?

### PR DESCRIPTION
**Pull request by yfried**
Fixes #454

### CODE REVIEW

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks for your contribution @yfried ☺️

**Comment by yfried** [comment]
@mumoshu Hi, what's the process for releasing a new chart version?

**Comment by mumoshu** [comment]
@yfried It isn't well defined but there's a GitHub Actions workflow that publishes a new chart version when it sees a git-commit that bumps the chart version number defined in `Chart.yaml`.

**Comment by mumoshu** [comment]
There are a few changes to the chart that coming from unreleased actions-runner-controller changes, no I was willing to publish the new chart version only after we released the new controller version this time. And the new controller version will be released a few weeks later.

Do you need the new chart version sooner?

**Comment by yfried** [comment]
@mumoshu 
1. I found some missing changes in my original PR. I'll submit them soon
2. If you could release a new chart once those are merged, it would help me greatly.

Thank you

**Comment by yfried** [comment]
@mumoshu 
1. I found some missing changes in my original PR. I'll submit them soon
2. If you could release a new chart once those are merged, it would help me greatly.

Thank you

**Pull request merged**
