### PR TITLE
docs: fixing malformed yaml in example templates

### PR DESCRIPTION
**Pull request by mitchell-phillips**
Our team was attempting to deploy horizontal scaling runners and the examples did not work.  We found it was an issue yaml having incorrect indentation.

[Issue #2379](https://github.com/actions/actions-runner-controller/issues/2379)

### CODE REVIEW

**Comment by mumoshu** [comment]
@mitchell-liatrio Hey! Thanks for your contribution. I reviewed your work but wasn't really sure how this can connect to https://github.com/actions/actions-runner-controller/issues/2379... Sorry, but could you confirm?

First, https://github.com/actions/actions-runner-controller/issues/2379 is about the deployment with the new charts and the new ARC mode that is being developed by the Actions team, and I believe it isn't available to public testers(including you) yet. See the chart name  `gha-runner-scale-set` mentioned in the issue. Are you really sure you're part of the private testing program?

Second, you fixed the yaml indentation in our documentation. But AFAIK, the additional two-space indentations there does not affect the semantic of the yaml documents. Could you give us the exact error message you received from what, and tell how your change fixed it..?

Thanks in advance for your help!

**Comment by mumoshu** [comment]
@mitchell-liatrio Hey! I'd still love your feedback on my previous comment so that we can move forward. Thanks in advance for your cooperation!

**Comment by mitchell-phillips** [comment]
Hey @mumoshu, 

I misunderstood #2379 and incorrectly marked it as the associated issue.

> Second, you fixed the yaml indentation in our documentation. But AFAIK, the additional two-space indentations there does not affect the semantic of the yaml documents. Could you give us the exact error message you received from what, and tell how your change fixed it..?

I won't have time to recreate the issue this week but as I recall, the HorizontalRunnerAutoscaller annotations for minReplicas and maxReplicas were not being respected.  Once I updated the indentation to follow YAML indentation rules, the correct minimum replicas were being created and scaled to the max under load as expected.

I can try and recreate the issue once I have time next week and upload supporting evidence of this issue.  My experience has been that indentation is very important in YAML, especially around Kubernetes manifests.  Let me know if you'd like me to pursue recreating this.

**Comment by mumoshu** [comment]
@mitchell-liatrio Hey! Thanks a lot for your confirmation. Yeah, I'd greatly appreciate it if you could recreate this with exact steps to reproduce the issue and the error message you encountered!

I know how yaml indentation is important, but speaking of the YAML docs you modified in this PR, they behave the same before/after the modification according to the yaml indentation rule and my own experience.

Let me close this for now. I'm looking forward to seeing your next PR! Thanks for your contribution.

**Pull request closed without merging**
