### PR TITLE
Add release note for ARC 0.27.0

### PR DESCRIPTION
**Pull request by mumoshu**
We're going to cut the new 0.27.0 release next week, and here's the release note that is intended to cover all the significant features and fixes included in it.

### CODE REVIEW

**Review by toast-gear — CHANGES_REQUESTED** [review]
Add in a note about the new ubuntu 22.04 runner images. The images aren't tied to v0.27.0 release itself so we'd need to sort of indicate that but it might be nice to highlight the fact they are a thing now and the UID and GID changes.

**Comment by ajschmidt8** [comment]
any updates on when this new release will be published?

**Review by TingluoHuang — APPROVED** [review]

**Comment by Link-** [comment]
An idea to consider, now that we have https://github.com/actions/actions-runner-controller/discussions/categories/announcements maybe we could also create an announcement there for this release?

**Comment by mumoshu** [comment]
@Link- Great idea! Shall we start by creating an announcement by copy-pasting the 0.27.0 release note and adding tweaks and corrections on demand?

**Comment by mumoshu** [comment]
Thanks for reviewing @TingluoHuang! Merging this now so that we have fewer things to do on Monday, which is the day we are planning to finally cut 0.27.0!

**Review by toast-gear — APPROVED** [review]

**Pull request merged**
