### PR TITLE
images: add linux arm/v7/v8 support

### PR DESCRIPTION
**Pull request by cpanato**
- images: add linux arm/v7/v8 support

Fixes: https://github.com/actions-runner-controller/actions-runner-controller/issues/1104

cc @mumoshu

### CODE REVIEW

**Comment by cpanato** [comment]
looks like this dependency does not have the arm available https://github.com/Yelp/dumb-init

**Comment by cpanato** [comment]
i will try to build locally, found other places that I was not aware when open this pr

**Comment by cpanato** [comment]
@mumoshu if the [dumb-init](https://github.com/Yelp/dumb-init) is required, I think we will need to close this pr because that does not have the arm support and the underlining dependencies for that also does not have (for context https://github.com/pypa/manylinux/issues/84) so will take some time :/

**Comment by mumoshu** [comment]
@cpanato Ah, good catch! I believe we don't have a strict requirement to stick with dumb-init. I thought there was a similar open source project that is written in Golang. IMHO a Golang-written alternative would have a better story on cross-platform.

**Comment by mumoshu** [comment]
@toast-gear has suggested using `tini` instead, and I think it's great!
The only gotcha would be that we need to pass `-g` to `tini` to make it compatible with our usage(and the default behavior of dumb-init)

https://github.com/Yelp/dumb-init#session-behavior
https://github.com/krallin/tini#process-group-killing

**Comment by cpanato** [comment]
sounds good! this is something you want to change and you want this in the project?

i will close this pr for now, thanks for all the support! 🎉

**Pull request closed without merging**
