### PR TITLE
Remove redundant flags from webhook-based autoscaler

### PR DESCRIPTION
**Pull request by mumoshu**
Ref #623

### CODE REVIEW

**Review by toast-gear — APPROVED** [review]

**Comment by toast-gear** [comment]
Actually just realised the values.yaml [charts/actions-runner-controller/README.md] docs have references to the old flags and need updating as part of this PR

**Review by toast-gear — CHANGES_REQUESTED** [review]
Actually just realised the values.yaml [charts/actions-runner-controller/README.md] docs have references to the old flags and need updating as part of this PR

**Comment by mumoshu** [comment]
@toast-gear Good catch! Fixed in 4f1d9ac

**Comment by mumoshu** [comment]
Thanks for reviewing ☺️

**Pull request merged**
