### PR TITLE
doc: Encourage everyone to explicitly set HRA scaleTargetRef kind

### PR DESCRIPTION
**Pull request by mumoshu**
Ref #1343

### CODE REVIEW

**Comment by kimxogus** [comment]
Is there an ETA for this PR?
`0.26.0` seems to be blocked by this.

**Comment by mumoshu** [comment]
@kimxogus Hey! We don't provide any ETA at the moment for anything. If you need 0.26.0 to be released earlier, it would be great if you could give it a shot using our `canary` image and the chart from the main branch. https://github.com/actions-runner-controller/actions-runner-controller/pull/1371#issuecomment-1210057401

**Comment by kimxogus** [comment]
@mumoshu Thanks! 👍

**Review by toast-gear — APPROVED** [review]

**Comment by mumoshu** [comment]
@toast-gear Thanks for reviewing!

**Pull request merged**
