### PR TITLE
feat: Set runner UID and docker GID to match github actions runner

### PR DESCRIPTION
**Pull request by suhasgaddam-trueaccord**
https://dev.to/jj/designing-containers-for-github-actions-5h84

Similar to https://github.com/actions-runner-controller/actions-runner-controller/pull/778#issue-983548504

Similar to https://github.com/aws/jsii/pull/3018

### CODE REVIEW

**Comment by mumoshu** [comment]
@suhasgaddam-trueaccord Hey! Thanks for submitting a pull request.
Would you mind clarifying what are the examples of exact issues & problems which can be fixed or addressed by this change?
Was there any specific error encountered in some action when uid/gid doesn't match with that of the managed actions runner? 🤔

**Comment by mumoshu** [comment]
@suhasgaddam-trueaccord Hey! Sorry for the long silence. I finally managed to pull some time to revisit this today.

I read https://github.com/actions-runner-controller/actions-runner-controller/pull/1688#issuecomment-120405220,1 several times and I'm now convinced that this should have been the default. Thanks a lot for the idea and for sharing the background. However, I can also see the point about some folks possibly relying on current `uid:gid` settings of `1000:1000`...

Probably a feasible way to move this forward would be to have another set of recommended runner images(probably with a unique suffix, like `summerwind/actions-runner-recommended:v$(RUNNER_VER)`) with `1001:121`, and encourage everyone to migrate to one of the recommended images ASAP, and eventually deprecate and remove the older images with 1000:1000.

Would you agree with that?

**Comment by mumoshu** [comment]
@suhasgaddam-trueaccord I'm gonna change the UID/GID part to refer to build args/env so that we can specify the UID/GID used in the image at build-time. After that, I would either try (1)publishing additional images with the new UID/GID along with existing images or (2) just add some instructions in our docs to explain how to build your custom images using alternative UID/GID. WDYT?

**Review by toast-gear — APPROVED** [review]

**Comment by toast-gear** [comment]
@suhasgaddam-trueaccord if you can rebase this we'll keep it at `1000` and `1001` for the 20.04 image and update them in the new 22.04 images

**Comment by mumoshu** [comment]
@suhasgaddam-trueaccord I've rebased this but I couldn't force-push the result to your branch. Let me open another pull request and continue the work there. Thanks again for your contribution!

**Comment by mumoshu** [comment]
Continued to #2077

**Pull request closed without merging**
