### PR TITLE
Don't set default caBundle for webhooks

### PR DESCRIPTION
**Pull request by jstewart612**
Fixes https://github.com/actions-runner-controller/actions-runner-controller/issues/614

### CODE REVIEW

**Comment by jstewart612** [comment]
@mumoshu Helm chart syncing functionalities do three-way merges of generated YAML.  When you specify a value for caBundle, it clobbers the value that the controller puts in there after it's setup.  This makes CD systems like ArgoCD and Flux unable to keep the Helm chart in sync because it enters a constant update loop for this value between rendered chart and the on-cluster value which the controller is setting.  This breaks the loop.

**Comment by mumoshu** [comment]
@jstewart612 Thanks for the PR! This looks good, except Helm 2. I know Helm 2 is already deprecated and perhaps not maintained anymore, but I want to prepare before being asked. That said..

> Helm chart syncing functionalities do three-way merges of generated YAML

What would happen when you run `helm upgrade` on the updated chart with helm 2, which doesn't support three-way merge? Override the caBundle field with an empty value?

**Comment by jstewart612** [comment]
Definitely not maintained anymore: https://helm.sh/blog/helm-v2-deprecation-timeline/

I don't know what happens, but feel it more than sufficient to no longer support that which is deprecated.

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks for the fix @jstewart612 ☺️

**Pull request merged**
