### PR TITLE
Fix link to 'detailed docs'

### PR DESCRIPTION
**Pull request by Vijay-train**

### CODE REVIEW

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks for fixing it!

**Comment by knkarthik** [comment]
@mumoshu I've found a bunch of broken links. I'm trying my best to fix them in https://github.com/actions-runner-controller/actions-runner-controller/pull/1882

**Comment by mumoshu** [comment]
@knkarthik Much appreciated! I'm going to review your awesome work ASAP

**Comment by Vijay-train** [comment]
Thank you @knkarthik and @mumoshu for fixing the links. 👍🏼

**Pull request merged**
