### PR TITLE
Stop unnecessary every-1-hour restart

### LINKED ISSUE #143: Runner restarts every hour
Hi, the github runners i have setup seem to be restarting every hour for no particular reason, they are not using used, seems like every hour or so they just restart. 

The first question i want to ask is if this is expected behavior or a bug?

### PR DESCRIPTION
**Pull request by mumoshu**
Fixes #143

### CODE REVIEW

**Comment by Hi-Fi** [comment]
I don't think current solution is a good thing, as now we never get new token (which is needed when runner is recreated).

I think `IsRegisterable` is OK, but it just needs to be called only before creating the new pod where token is actually needed.

**Comment by Hi-Fi** [comment]
I have thought this a bit, so if needed I can make PR about this refresh.

**Comment by Hi-Fi** [comment]
I think #159 solves this better.way

**Comment by mumoshu** [comment]
Closing in favor of #159. Thanks for your support @Hi-Fi ☺️

**Pull request closed without merging**
