### PR TITLE
Fix deleting a runner when pod was deleted

### PR DESCRIPTION
**Pull request by fgalind1**
With the current implementation if a pod is deleted, controller is failing to delete the runner as it's trying to annotate a pod that doesn't exist as we're passing a new pod object that is not an existing resource. We need to send `nil` if pod wasn't found to make sure we don't attempt to annotate a non-existing pod

### CODE REVIEW

**Comment by fgalind1** [comment]
@mumoshu do you know if something odd is going on with CI? interestingly a few different PRs started failing on the same after rebasing e.g this PR and this https://github.com/actions-runner-controller/actions-runner-controller/pull/1268

**Review by mumoshu — APPROVED** [review]
Makes sense! Thanks for the fix.
I thought we still needed `processRunnerDeletion` in that case to try unregister the runner for the disappeared pod, but turned out it's unnecessary because we now defer the registration to the runner pod controller.

**Comment by mumoshu** [comment]
@fgalind1 It seems like the setup-go action went wild (or we totally misunderstood how it's configured) that it's now installing go 1.18.x even though we specify go 1.17.x

CleanShot 2022-04-05 at 11 26 11@2x

The fact that `controller-gen` isn't found in the path even though the log says go built it might be due to that Go 1.18 changed `go get` to not install the binary.
We'd need to replace `go get` we use in Makefile to install controller-gen to `go install`.

**Comment by fgalind1** [comment]
> @fgalind1 It seems like the setup-go action went wild (or we totally misunderstood how it's configured) that it's now installing go 1.18.x even though we specify go 1.17.x
> 
> CleanShot 2022-04-05 at 11 26 11@2x
> 
> The fact that `controller-gen` isn't found in the path even though the log says go built it might be due to that Go 1.18 changed `go get` to not install the binary. We'd need to replace `go get` we use in Makefile to install controller-gen to `go install`.

interesting - thanks. This https://github.com/actions-runner-controller/actions-runner-controller/pull/1303 should at least unblock master branch and make sure there are no surprises. It's off because ^ should work and stick the minor version indeed as per semver docs

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for fixing it!

**Pull request merged**
