### PR TITLE
feat: 22.04 default runner image

### LINKED ISSUE #2006: Use ubuntu 22.04 as base image
### What would you like added?

Use ubuntu:22.04 as runners' base image

### Why is this needed?

Github hosted runners will use ubuntu 22.04 as `ubuntu-latest` soon

https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

### Additional context

*Add any other context or screenshots about the feature request here.*

### PR DESCRIPTION
**Pull request by toast-gear**
Depends on https://github.com/actions-runner-controller/actions-runner-controller/pull/2036 https://github.com/actions-runner-controller/actions-runner-controller/pull/2063

Resolves https://github.com/actions-runner-controller/actions-runner-controller/issues/2006

To Do
- [x] write up justification in this PR for why we've removed what we've removed and what the policy is going forward

**Preample**
A new Ubuntu version represents an opportunity for the ARC maintainers to cut down on the installed software in the runner. The existing runner images contain a lot of sofware that would not typically be needed in CI/CD environment or has a niche use case, by including it we get the following negatives:

1. a larger image for the sake of including some tools a small percentage of the consumers use
2. more points of failure
3. a more insecure base imaage

The software that is included in the runner as it is today was largely inherited and not active choices made by the current maintainers.

**Things Removed and Why**
build-essential - CI/CD unrelated / niche use case
dnsutils - CI/CD unrelated
ftp - CI/CD unrelated / niche use case
iproute2 - CI/CD unrelated
iputils-ping - CI/CD unrelated
libunwind8 - CI/CD unrelated
locales - CI/CD unrelated
netcat - CI/CD unrelated
openssh-client - CI/CD unrelated / niche use case
parallel - niche use case
rsync - CI/CD unrelated / niche use case
shellcheck - various actions exist to run shellcheck, too opinionated to be in the base runner  https://github.com/search?q=shellcheck+action https://github.com/github/super-linter
telnet - CI/CD unrelated
time - CI/CD unrelated
tzdata - CI/CD unrelated
upx - CI/CD unrelated
wget - we already bundle curl which covers the same use case
zstd - CI/CD unrelated

**Python**
python - there is a official set-up action for Python so no need to bundle it making the base image larger https://github.com/actions/setup-python
python3-pip - python has been removed

When our runner images were first produced GitHub Actions offered very poor support for managing runners and so there was a strong incentive for ARC to have a fatter more inclusive image over a slimmer image. Since those days GitHub has introduced the `--disableupdate` flag enabling ARC administrators to more easily use their own runners built from ours without significant operational impacts lessening the incentive to bundle as much as possible in the ARC runners themselves.

### CODE REVIEW

**Review by mumoshu — APPROVED** [review]
Perfect. Thanks as always for your awesome work ☺️

**Comment by totogtr** [comment]
Hi,

Any possibility to include back `openssh-client` ? It can be used to connect / upload some files to a remote machine.

**Comment by Gby56** [comment]
Hello, same here, I think we are using the summerwind image though, but we're seeing `asdf install` fail because `wget` is now missing ?

**Comment by corford** [comment]
Removing build-essential has broken a load of our CI/CD workflows that use `make`

**Pull request merged**
