### PR TITLE
chart: Create actionsmetrics.secrets.yaml

### PR DESCRIPTION
**Pull request by dhawalseth**
Adding the missing secret for actions metrics server which is reported in https://github.com/actions/actions-runner-controller/issues/2175

### CODE REVIEW

**Comment by dhawalseth** [comment]
@mumoshu Please review when you get a chance. Thanks!

**Review by mumoshu — DISMISSED** [review]
Awesome! Thank you very much for your efforts @dhawalseth ☺️

**Comment by dhawalseth** [comment]
@mumoshu can you please have this merged. thanks!

**Comment by remover** [comment]
@mumoshu would you have a rough idea of when this will be available? any workarounds in the meantime?

**Comment by heruscode** [comment]
@dhawalseth I think you still need to define `actions-runner-controller.actions-metrics-server.secretName` template in `_helpers.tpl`

**Comment by dhawalseth** [comment]
> @dhawalseth I think you still need to define `actions-runner-controller.actions-metrics-server.secretName` template in `_helpers.tpl`
Screenshot 2023-02-16 at 10 56 54 AM


Thanks did a rename using the existing name

**Comment by mrparkers** [comment]
any updates on this?  right now the chart for the standalone metrics server is broken without this change being merged.

thanks!

**Comment by cep21** [comment]
Hey we would also like this feature.  Any status updates on this PR?

**Comment by mumoshu** [comment]
Sorry I've been distracted by other fixes to the existing ARC features these days!
I'll test this locally soon and merge if it works for me.
In the meantime, any help in testing this would be much appreciated!
@mrparkers @remover @cep21 Have you already tested this in your environments? If so, sharing your experiences would help merging this earlier! Thanks.

**Comment by remover** [comment]
@mumoshu i've tested it and it no longer crashes for me:

```
╰─$ kubectl logs -n actions-runner-system actions-runner-controller-actions-metrics-server-dcdbfd887m6zb2
2023-02-23T17:08:34Z    INFO    -github-webhook-secret-token and GITHUB_WEBHOOK_SECRET_TOKEN are missing or empty. Create one following https://docs.github.com/en/developers/webhooks-and-events/securing-your-webhooks and specify it via the flag or the envvar
2023-02-23T17:08:48Z    INFO    workflowjobmetrics-webhookserver        ok      {"event": "workflow_job", "hookID": "401041881", "delivery": "bc873100-b39c-11ed-83a4-3cbb86376c23"}
2023-02-23T17:08:51Z    INFO    workflowjobmetrics-webhookserver        ok      {"event": "workflow_job", "hookID": "401041881", "delivery": "be10b730-b39c-11ed-9d77-a82827c34d99"}
2023-02-23T17:08:55Z    INFO    workflowjobmetrics-webhookserver        ok      {"event": "workflow_job", "hookID": "401041881", "delivery": "c0bc4f30-b39c-11ed-8025-5182e49f5423"}
2023-02-23T17:08:56Z    INFO    workflowjobmetrics-webhookserver        ok      {"event": "workflow_job", "hookID": "401041881", "delivery": "c1862ee0-b39c-11ed-847c-5a85dd79ec11"}
2023-02-23T17:09:00Z    INFO    workflowjobmetrics-eventreader  reading workflow_job logs       {"job_name": "lint", "job_id": "11555242811"}
2023-02-23T17:09:01Z    INFO    workflowjobmetrics-eventreader  reading workflow_job logs       {"job_name": "build", "job_id": "11555244132"}
```

from this i believe i can say that metrics are being recorded?

however, much like @dhawalseth, due to the lack of docs i've kind of hacked the implementation together.

would you by any chance have some advice on how to get the metrics into managed prometheus in gke? i'm following [this guide](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed) but no luck so far...

**Comment by mumoshu** [comment]
@remover Thanks for testing!

> would you by any chance have some advice on how to get the metrics into managed prometheus in gke? i'm following [this guide](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed) but no luck so far...

What did you try exactly? Did you create a ServiceMonitor for scraping actionsmetricsserver, or a PodMonitoring resource?

**Comment by remover** [comment]
> @remover Thanks for testing!
> 
> > would you by any chance have some advice on how to get the metrics into managed prometheus in gke? i'm following [this guide](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed) but no luck so far...
> 
> What did you try exactly? Did you create a ServiceMonitor for scraping actionsmetricsserver, or a PodMonitoring resource?

we got it working in the end (using `PodMonitoring`). i was a little disappointed at how slow the data becomes available to query in metrics explorer, though. it took on the order of minutes for the numbers to correctly reflect the values on the `/metrics` endpoint, even allowing for the caveat that they seem to mention [here](https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#counter-sums). if those are the real numbers i'm not sure managed prometheus is a viable option for this.

btw we noticed that the metrics deployment is [including the RBAC proxy](https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#counter-sums) based on [these values](https://github.com/actions/actions-runner-controller/blob/680a259db6c7e27482d3392b15b56b4fa7842837/charts/actions-runner-controller/values.yaml#L109-L116) rather than [these](https://github.com/actions/actions-runner-controller/blob/680a259db6c7e27482d3392b15b56b4fa7842837/charts/actions-runner-controller/values.yaml#L280-L291), which is what i would've expected.

**Comment by mumoshu** [comment]
Thanks for your response @remover!

> it took on the order of minutes for the numbers to correctly reflect the values on the /metrics endpoint, even allowing for the caveat that they seem to mention [here](https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#counter-sums). if those are the real numbers i'm not sure managed prometheus is a viable option for this.

Interesting! Out of curiosity, what was your scraping interval(probably it's configurable on GCP's managed prom offering), and what was the typical delay between the metrics exposed by actionsmetricsserver and those visible on the managed prom UI?


If it's like 30s scraping interavl and 5m delay, yeah I'm afraid it's less useful for real-time monitoring... (Although it's much better than nothing because it still allows you to trigger alerts to involve on-call engineers

> btw we noticed that the metrics deployment is [including the RBAC proxy](https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#counter-sums) based on [these values](https://github.com/actions/actions-runner-controller/blob/680a259db6c7e27482d3392b15b56b4fa7842837/charts/actions-runner-controller/values.yaml#L109-L116) rather than [these](https://github.com/actions/actions-runner-controller/blob/680a259db6c7e27482d3392b15b56b4fa7842837/charts/actions-runner-controller/values.yaml#L280-L291), which is what i would've expected.

Ohh good catch! We need to fix that. Thanks for reporting ☺️

**Comment by remover** [comment]
> Interesting! Out of curiosity, what was your scraping interval(probably it's configurable on GCP's managed prom offering), and what was the typical delay between the metrics exposed by actionsmetricsserver and those visible on the managed prom UI?

scrape internal was 15s, set via the `PodMonitoring` resource. i didn't measure the time delay exactly but it was certainly in the order of minutes. could easily have been around 5 mins for some time series... we were hoping to use this in a realtime capacity for load testing ARC and then afterwards just to monitor the queue depth. we really just want to understand how long engineers are having to wait for jobs to be picked up

**Review by mumoshu — APPROVED** [review]
LGTM! I've enhanced e2e test to cover the secret creation using helm and verified that it works.
Thank you for your contribution and patience @dhawalseth @remover and everyone involved!

**Comment by mrparkers** [comment]
Thanks for getting this merged!  When can we expect to see a new release of the chart that contains these fixes?

**Pull request merged**
