### PR TITLE
Set the AutoscalingRunnerSet name to runnerScaleSetName

### PR DESCRIPTION
**Pull request by hawkesn**
Relates to: https://github.com/actions/actions-runner-controller/issues/2802

This PR helps to rename the AutoscalingRunnerSet name based on the `runnerScaleSetName` but maintains the backwards compatibility of using the `Release.Name` if it hasn't been set by the user.

### CODE REVIEW

**Review by nikola-jokic — APPROVED** [review]
LGTM

**Comment by booleanbetrayal** [comment]
@nikola-jokic / @hawkesn - I just noticed that the `gha-runner-scale-set.labels` helper [still references](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/templates/_helpers.tpl#L30-L43) `.Release.Name`. I'm looking / needing this multiple subchart functionality, will this break any discovery or will the sets execute as expected?

**Comment by nikola-jokic** [comment]
Hey @booleanbetrayal,

It shouldn't break any functionality :relaxed:. However, thank you for noticing it! I'll create a PR fixing it for the next patch release.

**Comment by booleanbetrayal** [comment]
Thanks for the clarification @nikola-jokic !

**Pull request merged**
