### PR TITLE
Fix runner pod dnsConfig

### LINKED ISSUE #1224: Type of dnsConfig added in #764 wrong
It is set to "array" when it should be set to "object".  This makes it unusable and creates validation errors when specifying dnsConfig in normal PodSpec format using a map as normal.  Please correct.

### LINKED ISSUE #1226: dnsConfig doesn't seem to translate to created pods for the Runners
**Describe the bug**

With the following `RunnerDeployment` config snippet,

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: myorg-ephemeral-dns
  namespace: actions
spec:
  replicas: 1
  template:
    spec:
      organization: myorg
      labels:
        - myorg-onprem-dns
      dnsConfig:
        - options:
          - name: "ndots"
            value: "1"
```

... The `Runners` get created with the dnsConfig settings, but the associated pods do not.  I've experimented with different indenting and even other dnsConfig type settings, but nothing seems to translate to a change to the pod spec configuration or the actual `/etc/resolv.conf` file being changed.

I think we may be missing something like this in `controllers/runner_controller.go`, based on comparing this change with a [similar change](https://github.com/actions-runner-controller/actions-runner-controller/pull/456)

```go
	if len(runner.Spec.DnsConfig ) != 0 {
		pod.Spec.DnsConfig = runner.Spec.DnsConfig 
	}
```

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

Please see context in the description above.

**Expected behavior**

Expect to see the pods being created for the Runner(s) contain the appropriate dnsConfig settings as well as the actual pod execution runtime with the expected changes in `/etc/resolv.conf`

**Screenshots**

**Environment (please complete the following information):**
 - Controller Version: 0.20.4
 - Deployment Method: Helm
 - Helm Chart Version: 0.15.3

**Additional context**
I intend to submit a PR for what I think the fix may be.  Currently struggling with getting the make/environment to build properly (trying on both in MacOS and a linux VM without success)

### PR DESCRIPTION
**Pull request by billimek**
... this may be missing based on details from [this issue](https://github.com/actions-runner-controller/actions-runner-controller/issues/1226)

Fixes #1226
Fixes #1224

### CODE REVIEW

**Comment by billimek** [comment]
I've been unable to build this as a docker container against the Makefile/Dockerfile in the master branch due to strange errors that occur on MacOS, a linux VM, and even github codespaces all with the same error about a read-only filesystem:

```
RUN --mount=target=.   --mount=type=cache,mode=0777,target=${GOCACHE}   export GOOS=${TARGETOS} GOARCH=${TARGETARCH} GOARM=${TARGETVARIANT#v} &&   go build -o /out/manager main.go &&   go build -o /out/github-webhook-server ./cmd/githubwebhookserver:                                           
#13 0.428 container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/var/lib/docker/overlay2/ygto3kzjlp7rm7fq3guf88gdb/merged/cache" to rootfs at "/workspace/${GOCACHE}" caused: mkdir /var/lib/docker/buildkit/executor/cncbc4ch5a1h2ysgmn7zb8i3v/rootfs/workspace/${GOCACHE}: read-only file system
```

image

However, I was able to apply the changes and build against the Makefile/Dockerfile based off of the code in the `v0.21.1` tag.  Using this, and the associated built and pushed actions-runner-controller docker image (`billimek/actions-runner-controller:dnsConfig-b25a0fd6`) & changed CRDs, I was able to successfully run and apply the dnsConfig in my actions-runner-controller environment

**Comment by splitice** [comment]
I've also got a similar issue trying to build (linu docker)

**Comment by billimek** [comment]
I think I sorted the local build issues by using the `make docker-buildx` (vs `make docker-build`).

We've been running the backported fix now in our org-wide runners without issue and would love to see what next steps are necessary to progress this PR?

**Comment by toast-gear** [comment]
Have you actually tried installing this? Haven't digged into it yet but I get the below error when trying to install your branch's chart:

```
Error: failed to install CRD crds/actions.summerwind.dev_runnerreplicasets.yaml: CustomResourceDefinition in version "v1" cannot be handled as a CustomResourceDefinition: v1.CustomResourceDefinition.Spec: v1.CustomResourceDefinitionSpec.Versions: []v1.CustomResourceDefinitionVersion: v1.CustomResourceDefinitionVersion.Schema: v1.CustomResourceValidation.OpenAPIV3Schema: v1.JSONSchemaProps.Properties: v1.JSONSchemaProps.Properties: v1.JSONSchemaProps.Properties: v1.JSONSchemaProps.Properties: v1.JSONSchemaProps.Properties: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|},"type":"object"},"|..., bigger context ...|items":{"type":"string"},"type":"array"}},"type":"object"},"type":"array"},"dockerEnabled":{"type":"|...
```

**Comment by billimek** [comment]
I think the latest merge from master requires an additional generation of the replica set CRD. I know what to do. Will push a working update today. 

FWIW we are running these changes "in prod" everywhere now without issue. Can't wait to eventually go back to the official image & code!

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for your contribution @billimek ☺️

**Pull request merged**
